"""create task rules table

Revision ID: a51ac3589f9a
Revises: d980496a7ab2
Create Date: 2026-06-01 12:51:15.994555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51ac3589f9a'
down_revision: Union[str, None] = 'd980496a7ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('min_experience', sa.Integer(), nullable=True),
    sa.Column('max_active_tasks', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_rules_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_rules_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_rules_max_active_tasks'), ['max_active_tasks'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_rules_min_experience'), ['min_experience'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_rules_min_experience'))
        batch_op.drop_index(batch_op.f('ix_task_rules_max_active_tasks'))
        batch_op.drop_index(batch_op.f('ix_task_rules_location'))
        batch_op.drop_index(batch_op.f('ix_task_rules_department'))

    op.drop_table('task_rules')
    # ### end Alembic commands ###
